name: Publish Docker image

on:
    workflow_dispatch:
        inputs:
            tags:
                description: Additional image tags (e.g. "latest")
                required: false
                type: string
            build_args:
                description: Build-time variables
                required: false
                type: string
    workflow_call:
        inputs:
            tags:
                description: Additional image tags (e.g. "latest")
                required: false
                type: string
            build_args:
                description: Build-time variables
                required: false
                type: string

env:
    NAME: 'custody-blockscout-frontend'
    ACR_NAME: solidstate
    AZURE_CLIENT_ID: '8e619a41-08e8-46d0-b38d-dd4185432cac'
    AZURE_TENANT_ID: 'ea2aa545-c271-48b3-880d-0b56c78e4d9c'
    AZURE_SUBSCRIPTION_ID: 'a5d084b6-9c2f-4792-997b-3b17c7854ab2'

permissions:
    id-token: write
    contents: read

jobs:
    run:
        name: Build and Push
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4

            -   name: Add SHORT_SHA env property with commit short sha
                run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

            -   name: Login to Azure
                uses: azure/login@v2
                with:
                    client-id: ${{ env.AZURE_CLIENT_ID }}
                    tenant-id: ${{ env.AZURE_TENANT_ID }}
                    subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

            -   name: Login to ACR
                run: az acr login --name $ACR_NAME

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Build and push Docker image
                run: |
                    TAG="${{ github.ref_type == 'tag' && github.ref_name || github.sha }}"
                    docker build \
                        -t $ACR_NAME.azurecr.io/$NAME:${{ github.sha }} \
                        -t $ACR_NAME.azurecr.io/$NAME:$TAG \
                        ${{ inputs.tags != '' && format('-t {0}.azurecr.io/{1}:{2}', env.ACR_NAME, env.NAME, inputs.tags) || '' }} \
                        --build-arg GIT_COMMIT_SHA=${{ env.SHORT_SHA }} \
                        --build-arg GIT_TAG=${{ github.ref_type == 'tag' && github.ref_name || '' }} \
                        ${{ inputs.build_args }} \
                        -f Dockerfile .
                    docker push $ACR_NAME.azurecr.io/$NAME --all-tags
