name: Release

on:
    workflow_dispatch:
    release:
        types: [ released ]

jobs:
    publish_image:
        name: Publish Docker image
        uses: './.github/workflows/publish-image.yml'
        secrets: inherit
        with:
            tags: latest
        permissions:
            id-token: write
            contents: read
